# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: feiyu's blog | VolitantFish
subtitle: 如何串联已有认知来服务新需求，是我一直关注的，并且这过程让我乐此不疲。
description: feiyu's blog
keywords: 博客, blog, feiyu, iamfeiyu
author: feiyu
language: zh-CN
timezone: ''


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.iamfeiyu.top          # url: https://iamfeiyu.github.io
root: /
# 下面四行是文章永久链接：方案二的设置
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
# 下面三行是文章永久链接：方案一的设置
# permalink: posts/:urlname/
# permalink_defaults: 
#   urlname: index
# 下面两行是默认设置
#permalink: :year/:month/:day/:title/
#permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next-8.0.0-rc.4

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/iamfeiyu/iamfeiyu.github.io.git
  branch: master
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  user: iamfeiyu
  email: dhydghdq@outlook.com

# 设置Hexo支持aplayer音乐播放器（支持Meting，解析中国各大音乐平台接口）
aplayer:
  meting: true         # Meting support, default: false
# ---------------------------------------------------------------
# Next主题的配置项
# ---------------------------------------------------------------
theme_config:
  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  # External url should start with http:// or https://
  menu:
    home: / || home
    archives: /archives/ || archive
    categories: /categories/ || th
    tags: /tags/ || tags
    playlist: /playlist/ || music
    about: /about/ || user
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat