# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: feiyu's blog | VolitantFish
subtitle: 如何串联已有知识来服务新需求，是我一直关注的，并且这过程让我乐此不疲。
description: feiyu's blog
keywords: 博客, blog, feiyu, iamfeiyu
author: feiyu
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.iamfeiyu.top          # url: https://iamfeiyu.github.io
root: /
# 下面四行是文章永久链接：方案二的设置
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
# 下面三行是文章永久链接：方案一的设置
# permalink: posts/:urlname/
# permalink_defaults: 
#   urlname: index
# 下面两行是默认设置
# permalink: :year/:month/:day/:title/
# permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next-7.2.0

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/iamfeiyu/iamfeiyu.github.io.git
  branch: master
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  user: iamfeiyu
  email: dhydghdq@outlook.com

# 设置Hexo支持aplayer音乐播放器（支持Meting，解析中国各大音乐平台接口）
aplayer:
  meting: true         # Meting support, default: false

# Local Search
# 搜索插件 hexo-generator-searchdb
# see https://github.com/theme-next/hexo-generator-searchdb
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Symbols_count_time 站点配置中打开文章字数统计、阅读时间估算统计
symbols_count_time:
  symbols: true
  time: false
  total_symbols: false
  total_time: false
  exclude_codeblock: false

# ---------------------------------------------------------------
# Next主题的配置项
# ---------------------------------------------------------------
theme_config:

  # ---------------------------------------------------------------
  # Site Information Settings
  # See: https://theme-next.org/docs/getting-started/
  # ---------------------------------------------------------------

  favicon:
    small: uploads/images/favicon-16x16-next.png
    medium: uploads/images/favicon-32x32-next.png
    apple_touch_icon: uploads/images/apple-touch-icon-next.png
    safari_pinned_tab: uploads/images/logo.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    since: 2018

    # Icon between year and copyright info.
    icon:
      # Icon name in fontawesome, see: https://fontawesome.com/v4.7.0/icons/
      # `heart` is recommended with animation in red (#ff0000).
      name: user
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#808080"

    # If not defined, `author` from Hexo main config will be used.
    copyright: feiyu

    powered:
      # Hexo link (Powered by Hexo).
      enable: false
      # Version info of Hexo after Hexo link (vX.X.X).
      version: false

    theme:
      # Theme & scheme info link (Theme - NexT.scheme).
      enable: false
      # Version info of NexT after scheme info (vX.X.X).
      version: false

  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  # You can set a language value if you prefer a translated version of CC license.
  # CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
  # Valid values of language: deed.zh, deed.fr, deed.de, etc.
  creative_commons:
    license: by-nc-sa
    sidebar: false
    post: true
    language:

  # `Follow me on GitHub` banner in the top-right corner.
  github_banner:
    enable: true
    permalink: https://github.com/iamfeiyu
    title: Follow me on GitHub

  # ---------------------------------------------------------------
  # SEO Settings
  # ---------------------------------------------------------------

  # Disable Baidu transformation on mobile devices.
  disable_baidu_transformation: false

  # Set a canonical link tag in your hexo, you could use it for your SEO of blog.
  # See: https://support.google.com/webmasters/answer/139066
  # Tips: Before you open this tag, remember set up your URL in hexo _config.yml (e.g. url: http://yourdomain.com)
  canonical: true

  # Change headers hierarchy on site-subtitle (will be main site description) and on all post / page titles for better SEO-optimization.
  seo: true

  # If true, will add site-subtitle to index page, added in main hexo config.
  # subtitle: Subtitle
  index_with_subtitle: true

  # Automatically add external URL with BASE64 encrypt & decrypt.
  exturl: true
  
  # Google Webmaster tools verification.
  # See: https://www.google.com/webmasters
  google_site_verification: GPQKjVjUxa8f14eEVWyI0LuiNjRuo2UAlLZauruei0g

  # Bing Webmaster tools verification.
  # See: https://www.bing.com/webmaster
  #bing_site_verification:

  # Yandex Webmaster tools verification.
  # See: https://webmaster.yandex.ru
  #yandex_site_verification:

  # Baidu Webmaster tools verification.
  # See: https://ziyuan.baidu.com/site
  baidu_site_verification: beN3QJi3nu

  # Enable baidu push so that the blog will push the url to baidu automatically which is very helpful for SEO.
  baidu_push: true
  
  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash from link value (/archives -> archives).
  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimeter is the target link.
  # Value after `||` delimeter is the name of FontAwesome icon. If icon (with or without delimeter) is not specified, question icon will be loaded.
  # External url should start with http:// or https://
  menu:
    home: / || home
    archives: /archives/ || archive
    categories: /categories/ || th
    tags: /tags/ || tags
    playlist: /playlist/ || music
    about: /about/ || user
    #schedule: /schedule/ || calendar
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini

  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  social:
    GitHub: https://github.com/iamfeiyu || github
    E-Mail: mailto:emailFeiyu@163.com || envelope
    #Weibo: https://weibo.com/yourname || weibo
    #Google: https://plus.google.com/yourname || google
    #Twitter: https://twitter.com/yourname || twitter
    #FB Page: https://www.facebook.com/yourname || facebook
    #VK Group: https://vk.com/yourname || vk
    #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
    #YouTube: https://youtube.com/yourname || youtube
    #Instagram: https://instagram.com/yourname || instagram
    #Skype: skype:yourname?call|chat || skype

  # Blog rolls
  links_icon: link
  links_title: 推荐阅读
  #links_layout: block
  links_layout: inline
  links:
    UZER.ME: https://uzer.me/u/signin
    导航湾: http://daohangwan.com/board/bq2d
    #Title: http://example.com

  # Sidebar Avatar
  avatar:
    # In theme directory (source/images): /images/avatar.gif
    # In site directory (source/uploads): /uploads/avatar.gif
    # You can also use other linking images.
    url: uploads/images/avatar.jpg
    # If true, the avatar would be dispalyed in circle.
    rounded: true
    # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
    opacity: 1
    # If true, the avatar would be rotated with the cursor.
    rotated: true

  back2top:
    enable: true
    # Back to top in sidebar.
    sidebar: false
    # Scroll percent label in b2t button.
    scrollpercent: true

  # Post Settings
  # Automatically Excerpt (Not recommend).
  # Use <!-- more --> in the post to control excerpt accurately.
  auto_excerpt:
    enable: true
    length: 150

  # Post meta display settings
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: false
      another_day: false
    categories: true   #文章开头显示分类于

  # Post wordcount display settings 主题配置文件中设置文章字数统计、阅读时间估算统计
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false
    awl: 2
    wpm: 300
    suffix: mins.

  # 设置代码块圆角及复制按钮是否显示
  codeblock:
    # Manual define the border radius in codeblock, leave it blank for the default value: 1
    border_radius:
    # Add copy button on codeblock
    copy_button:
      enable: false
      # Show text copy result
      show_result: false
      # Style: only 'flat' is currently available, leave it blank if you prefer default theme
      style:

  # Use icon instead of the symblo # to indicate the tag at the bottom of the post
  tag_icon: true

  # Wechat Subscriber 微信账号二维码/微信公众号二维码/关注微信公众号
  wechat_subscriber:
    enable: false
    # qcode: uploads/images/wechat-subscriber-qcode.jpg
    # description: 欢迎关注我公众号！ # e.g. subscribe to my blog by scanning my public wechat account

  # Reward (Donate) 奖励二维码的设置
  reward_settings:
    # If true, reward would be displayed in every article by default.
    # You can show or hide reward in a specific article throuth `reward: true | false` in Front-matter.
    enable: true
    animation: true
    comment: 您的支持将鼓励我继续创作！

  reward:
    wechatpay: uploads/images/wechatpay.jpg
    alipay: uploads/images/alipay.jpg
    #bitcoin: /images/bitcoin.png

  # ---------------------------------------------------------------
  # Third Party Services Settings 第三方服务库配置
  # See: https://theme-next.org/docs/third-party-services/
  # You may need to install dependencies or set CDN URLs in `vendors`
  # There are two different CDN providers by default:
  #   - jsDelivr (cdn.jsdelivr.net), works everywhere even in China
  #   - CDNJS (cdnjs.cloudflare.com), provided by cloudflare
  # ---------------------------------------------------------------

  # ---------------------------------------------------------------
  # Comments and Widgets 评论系统与小部件
  # See: https://theme-next.org/docs/third-party-services/comments-and-widgets
  # ---------------------------------------------

  # LiveRe comments system 来必力评论系统
  # You can get your uid from https://livere.com/insight/myCode (General web site)
  livere_uid: MTAyMC80NTQzNy8yMTk0OQ==

  # ---------------------------------------------------------------
  # Content Sharing Services 文章分享服务
  # See: https://theme-next.org/docs/third-party-services/content-sharing-services
  # ---------------------------------------------------------------

  #needmoreshare2_js:
  #needmoreshare2_css: 
  # NeedMoreShare2
  # Dependencies: https://github.com/theme-next/theme-next-needmoreshare2
  # iconStyle: default | box
  # boxForm: horizontal | vertical
  # position: top / middle / bottom + Left / Center / Right
  # networks:
  # Weibo,Wechat,Douban,QQZone,Twitter,Facebook,Linkedin,Mailto,Reddit,Delicious,StumbleUpon,Pinterest,
  # GooglePlus,Tumblr,GoogleBookmarks,Newsvine,Evernote,Friendfeed,Vkontakte,Odnoklassniki,Mailru
  needmoreshare2:
    enable: true
    postbottom:
      enable: true
      options:
        iconStyle: box
        boxForm: horizontal
        position: bottomCenter
        networks: Weibo,Wechat,Linkedin,Douban,Evernote,Twitter,Facebook
    float:
      enable: false
      options:
        iconStyle: box
        boxForm: vertical
        position: topRight
        networks: Weibo,Wechat,Linkedin,Douban,Evernote,Twitter,Facebook

  # ---------------------------------------------------------------
  # Statistics and Analytics 统计与分析
  # See: https://theme-next.org/docs/third-party-services/statistics-and-analytics
  # ---------------------------------------------------------------

  # Statistics and Analytics 设置页面底部统计项：浏览量
  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: user
    total_views: true
    total_views_icon: eye
    post_views: true
    post_views_icon: eye

  # ---------------------------------------------------------------
  # Search Services 搜索服务设置
  # See: https://theme-next.org/docs/third-party-services/search-services
  # ---------------------------------------------------------------

  # Local search 本地搜索加载到主题中
  # Dependencies: https://github.com/theme-next/hexo-generator-searchdb
  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 1
    # Unescape html strings to the readable one.
    unescape: false

  # ---------------------------------------------------------------
  # Tags Settings 主题标签插件设置
  # See: https://theme-next.org/docs/tag-plugins/
  # ---------------------------------------------------------------

  # Tabs tag
  tabs:
    enable: true
    transition:
      tabs: false
      labels: true
    border_radius: 0

  # ---------------------------------------------------------------
  # Animation Settings 主题动画设置
  # ---------------------------------------------------------------

  # Use velocity to animate everything.
  motion:
    enable: true
    async: false
    transition:
      # Transition variants:
      # fadeIn | fadeOut | flipXIn | flipXOut | flipYIn | flipYOut | flipBounceXIn | flipBounceXOut | flipBounceYIn | flipBounceYOut
      # swoopIn | swoopOut | whirlIn | whirlOut | shrinkIn | shrinkOut | expandIn | expandOut
      # bounceIn | bounceOut | bounceUpIn | bounceUpOut | bounceDownIn | bounceDownOut | bounceLeftIn | bounceLeftOut | bounceRightIn | bounceRightOut
      # slideUpIn | slideUpOut | slideDownIn | slideDownOut | slideLeftIn | slideLeftOut | slideRightIn | slideRightOut
      # slideUpBigIn | slideUpBigOut | slideDownBigIn | slideDownBigOut | slideLeftBigIn | slideLeftBigOut | slideRightBigIn | slideRightBigOut
      # perspectiveUpIn | perspectiveUpOut | perspectiveDownIn | perspectiveDownOut | perspectiveLeftIn | perspectiveLeftOut | perspectiveRightIn | perspectiveRightOut
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideRightIn #slideUpIn

  # Fancybox 灯箱效果看图（点击图片全屏看图）
  fancybox: true

  # Reading progress bar 阅读进度
  # Dependencies: https://github.com/theme-next/theme-next-reading-progress
  reading_progress:
    enable: true
    color: "#37c6c0"
    height: 2px

  # Online contact 设置在线匿名对话功能
  daovoice: true
  daovoice_app_id: efb1e7fd

  # 文章末尾添加“本文结束”标记
  passage_end_tag:
    enabled: true
